In [2]:
import numpy as np
n1 = np.array([1,2,3])
n1

array([1, 2, 3])

In [8]:
# Initialize the numpy array with all zeros
import numpy as np
n2 = np.zeros((1,2))
n2

array([[0., 0.]])

In [10]:
# Initialize the numpy array with all the  same numbers
import numpy as np
n3= np.full((5,5),7)
n3

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [20]:
#Example of the arange method
import numpy as np
n1 = np.arange(10,15)
print(n1)
n2 = np.arange(10,51,10)
print(n2)

[10 11 12 13 14]
[10 20 30 40 50]


In [98]:
#To change the shape of an array use SHAPE method
n = np.array([[1,2,3],
              [4,5,6]])
n.shape = (2,3)
print(n)

[[1 2 3]
 [4 5 6]]


In [100]:
#use random  
n = np.random.randint(10,1000,10)
print(n)


[605 420 402 478 941 378 181 261 494 553]
